# This is a config for E2B sandbox template.
# You can use 'template_id' (notm15sx41bgzwyizzf1) or 'template_name (hummingbird) from this config to spawn a sandbox:

# Python SDK
# from e2b import Sandbox
# sandbox = Sandbox(template='hummingbird')

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create({ template: 'hummingbird' })

dockerfile = "e2b.Dockerfile"
template_name = "hummingbird"
template_id = "notm15sx41bgzwyizzf1"
